language: c
sudo: false

addons:
  chrome: stable
  #firefox: latest

env:
  global:
    - CONDA_DEPS="numpy pytest"
    - PIP_DEPS="selenium pyimgur"
    - GECKODRIVER_VER="v0.19.1"

matrix:
  include:
    - env: PYTHON="2.7"
    - env: PYTHON="3.5"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME/miniconda"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test python="$PYTHON" pip
  - source activate test
  #- wget "https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-$GECKODRIVER_VER-linux64.tar.gz"
  #- mkdir geckodriver
  #- tar -xzf "geckodriver-$GECKODRIVER_VER-linux64.tar.gz" -C geckodriver
  #- export PATH=$PATH:$PWD/geckodriver
  - wget "https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip"
  - mkdir chromedriver
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=$PATH:$PWD/chromedriver
  - export MOZ_CRASHREPORTER_SHUTDOWN=1
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  #- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16
  - sleep 3
  - echo $DISPLAY
  #- firefox -marionette

install:
  - eval conda install "$CONDA_DEPS"
  - eval pip install "$PIP_DEPS"

bfore_script:
  #- wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
  #- java -jar selenium-server-standalone-2.53.1.jar > /dev/null &
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  #- sleep 3  # give xvfb and some time to start

script:
  - python setup.py -q develop
  - pytest -v -x -s
